### PR TITLE
Fix softmax

### PR DESCRIPTION
**Pull request by thomasw21**
@hyunwoongko has provided a fix for gpt-neox https://github.com/EleutherAI/gpt-neox/pull/572. I think the same fix applies to us. I think this might have affect the throughput in some ways.

@hyunwoongko feel free to correct my if i'm wrong.

### CODE REVIEW

**Comment by stas00** [comment]
Thank you for detecting that we missed that upstream fix, @thomasw21. 

Since I originally applied the first batch of these fixes, I tried to see what else was missing and discovered a lot more of those and I'm trying a different approach here:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/260

**Comment by thomasw21** [comment]
Thanks @stas00 I think we can merge these fixes on your branch if your prefer. (I think they are relevant and not covered by your PR)

**Comment by stas00** [comment]
Yes, and there are more fixes in this file besides what you added - I'm checking what else might need to go in there and updating my PR.

**Comment by thomasw21** [comment]
Closing in favor of https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/260

**Pull request closed without merging**
