### PR TITLE
removed regular package for megatron model

### PR DESCRIPTION
**Pull request by jtboing**
Removed regular package (__init__.py) on megatron model subfolder and adapted calls for imports in various scripts.

### CODE REVIEW

**Comment by stas00** [comment]
oh, this fell between cracks, my apologies.

but I have no perms to push into this branch... I will try to copy it

**Comment by stas00** [comment]
continued at https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/192

**Comment by jtboing** [comment]
> oh, this fell between cracks, my apologies.
> 
> but I have no perms to push into this branch... I will try to copy it
> 
> I replayed it here via cherry-pick so the credits are set correctly to the original author: #192

I see. It is because of the branches? Or is it because of branches from my fork?

**Comment by stas00** [comment]
Typically this means that your PR from your private fork was set to not allow maintainers to push. Usually it's a setting on the right side.

**Comment by jtboing** [comment]
Right. Thanks for the tip, I'll try to set this option to make it more convenient.

**Pull request closed without merging**
