### PR TITLE
training with dummy data to verify sampling

### PR DESCRIPTION
**Pull request by lintangsutawika**
Added a few scripts to verify multi-data sampling is correct.

### CODE REVIEW

**Comment by stas00** [comment]
@lintangsutawika, please place the scripts under:

https://github.com/bigscience-workshop/Megatron-DeepSpeed/tree/main/scripts

after creating a sub-folder for a specific sub-topic if it's not there already.

Thank you.

**Comment by stas00** [comment]
Great to see some tests - we are waiting for the Deepspeed repo to create a CI which we will then plan to replicate.

**Comment by lintangsutawika** [comment]
@stas00 test moved to scripts/

**Comment by stas00** [comment]
Thank you, @lintangsutawika

**Comment by sbmaruf** [comment]
@stas00 Should we merge this branch?

**Pull request merged**
